name: EDIFACT_release
permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Build
        run: dotnet build
        working-directory: Netum.Truugo.EDIFACT
      - name: Test
        run: dotnet test
        working-directory: Netum.Truugo.EDIFACT
        env:
          TRUUGO_API_USERNAME: ${{ secrets.TRUUGO_API_USERNAME }}
          TRUUGO_API_PASSWORD: ${{ secrets.TRUUGO_API_PASSWORD }}
          EDIFACT_TEST_FILE_NAME: ${{ secrets.EDIFACT_TEST_FILE_NAME }}
