name: Validator_test_on_main
permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - 'Netum.Truugo.Validator/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_main.yml@main
    with:
      workdir: Netum.Truugo.Validator
      dotnet_version: 8.0.x
      strict_analyzers: true
      env_var_name_1: TRUUGO_API_USERNAME
      env_var_name_2: TRUUGO_API_PASSWORD
      env_var_name_3: TRUUGO_API_PROFILE_KEY
      env_var_name_4: VALIDATOR_TEST_FILE_NAME
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      env_var_value_1: ${{ secrets.TRUUGO_API_USERNAME }}
      env_var_value_2: ${{ secrets.TRUUGO_API_PASSWORD }}
      env_var_value_3: ${{ secrets.TRUUGO_API_PROFILE_KEY }}
      env_var_value_4: ${{ secrets.VALIDATOR_TEST_FILE_NAME }}
